spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/incense_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: root
      password: ssafy
#    password: root       # YURIM
    driver-class-name: com.mysql.cj.jdbc.Driver